GET http://localhost:9090/api/feeds HTTP/1.1
###

GET http://localhost:9090/api/feeds//article/bb087d5e-c073-45d0-a2fd-8987b6aa69b0 HTTP/1.1
###

GET  http://localhost:9090/api/feeds//articles/update HTTP/1.1
###

GET http://localhost:9090/api/feeds/pageable?page=0&size=6 HTTP/1.1
###

GET http://localhost:9090/api/feeds/user/vangel12/pageable?page=0&size=6 HTTP/1.1
###

POST http://localhost:9090/api/feeds HTTP/1.1
Content-Type: application/json

{
    "url":"https://www.polygon.com/rss/index.xml"
}
###

DELETE http://localhost:9090/api/feeds/a945b018-459b-4607-a68d-92249e9a51fc HTTP/1.0
###